#! bash

### DO NOT EDIT
### This file was generated by complete-shell-generate-bash v0.0.0

_complete_ltc() {
  __complete_shell_add_subcommands "box destroy halt help init package plugin provision reload resume ssh ssh-config status suspend up"
}
