#! bash

### DO NOT EDIT
### This file was generated by complete-shell-tools-bash v0.0.0

__complete-shell::vagrant() {
  echo \
    box destroy halt help init package plugin provision \
    reload resume ssh ssh-config status suspend up
}
